config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
 # nothing is required for movies
  root 'lists#index' # This makes the default page change to home page
  resources :lists, only: [:index, :new, :create, :show] do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie, presence: true, uniqueness: { scope: :list }

end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
before_action :set_bookmark, only: :destroy
before_action :set_list, only: [:new, :create]


def new
  @bookmark = Bookmark.new
end

def create
  @bookmark = Bookmark.new(bookmark_params)
  # @list = List.find(params[:list_id])
  @bookmark.list = @list
  if @bookmark.save
    redirect_to list_path(@list)
  else
    render :new, status: :unprocessable_entity
  end
end

def destroy
  @bookmark = Bookmark.find(params[:id])
  @bookmark.destroy
  redirect_to @bookmark.list
end



private

def set_list
  @list = List.find(params[:list_id])
end



def bookmark_params
  params.require(:bookmark).permit(:movie_id, :comment)
end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController



def index
  @lists = List.all
end

def show
  @list = List.find(params[:id])
  @bookmarks = @list.bookmarks

  # This bookmark is for the form
  @bookmark = Bookmark.new
end

def new
  @list = List.new
end

def create
  @list = List.new(list_params)
  if @list.save
    redirect_to lists_path
  else
    render :show, status: :unprocessable_entity
  end
end


private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

  def set_list
    @list = List.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://t4.ftcdn.net/jpg/02/57/52/11/360_F_257521199_oYHHL4owRzuWSz6TeEUQxxr7HBM9b8JG.jpg);">
  <div class="container">
    <h1>The LIST</h1>
    <p>Learn what other people like and judge!</p>

  </div>
  </div>

<div class="list text-center">
  <% @lists.each do |list|%>
    <%= link_to list.name, list_path(list), class:"black" %>
  <% end %>
</div>

<%= link_to new_list_path, class: "btn btn-success",id:"button" ,  style: "margin-top: 30px;" do %>
  <i class="bi bi-plus-lg"></i> Make a New List
<% end %>

app/views/lists/new.html.erb
<h1>Make a New List</h1>



<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
    <%= f.input :photo, as: :file %>
   <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<% if @list.photo.attached? %>
  <%= cl_image_tag(@list.photo.key,
  width: 400, height: 300, crop: :fill)%>
<% else %>
  <%= image_tag 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPQDYau3Hs4-xw1i8jVSUY4BlF4FLmg8lQqg&usqp=CAU' %>
<% end %>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
   <%= f.submit class: 'btn btn-primary' %>
<% end %>

<% @bookmarks.each do |bookmark|%>
<%= bookmark.movie.title %>
  <%= bookmark.comment  %>
   <%= link_to 'Delete', bookmark_path(bookmark), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
  <%end %>



<%=link_to "Go Back", lists_path%>